{"modules": [{"name": "tests_tp1", "nr_success": 3, "nr_failed": 1, "nr_error": 7, "testcases": [{"name": "test_premier", "result": "success"}, {"name": "test_parfait", "result": "success"}, {"name": "test_chanceux", "result": "success"}, {"name": "test_amis", "result": "failed", "error": {"message": "AssertionError: False != [(220, 284), (1184, 1210), (2620, 2924)]", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 17, "function": "test_amis", "line": "eq_(amis(5000), [(220, 284), (1184, 1210), (2620, 2924)])"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\tools\\trivial.py", "linenr": 29, "function": "eq_", "line": "raise AssertionError(msg or \"%r != %r\" % (a, b))"}]}}, {"name": "test_tous", "result": "error", "error": {"message": "NameError: name 'tous' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 20, "function": "test_tous", "line": "eq_(tous(lambda x: x % 2 == 0, 17), [2, 4, 6, 8, 10, 12, 14, 16])"}]}}, {"name": "test_premiers", "result": "error", "error": {"message": "NameError: name 'premiers' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 25, "function": "test_premiers", "line": "eq_(premiers(20), expected)"}]}}, {"name": "test_parfaits", "result": "error", "error": {"message": "NameError: name 'parfaits' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 28, "function": "test_parfaits", "line": "eq_(parfaits(1000), [6, 28, 496])"}]}}, {"name": "test_tous_chanceux", "result": "error", "error": {"message": "NameError: name 'tous_chanceux' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 31, "function": "test_tous_chanceux", "line": "eq_(tous_chanceux(100), [2, 3, 5, 11, 17, 41])"}]}}, {"name": "test_erathos", "result": "error", "error": {"message": "NameError: name 'erathos' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 35, "function": "test_erathos", "line": "eq_(erathos(20), expected)"}]}}, {"name": "test_encode", "result": "error", "error": {"message": "NameError: name 'decode' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 38, "function": "test_encode", "line": "eq_(decode(encode(\"Bonjour \u00e0 tous\", 7), 7), \"Bonjour \u00e0 tous\")"}]}}, {"name": "test_rot13", "result": "error", "error": {"message": "NameError: name 'rot13' is not defined", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp1\\tests_tp1.py", "linenr": 41, "function": "test_rot13", "line": "eq_(rot13(\"Bonjour \u00e0 tous\"), 'Obawbhe \u00e0 gbhf')"}]}}]}], "metadata": {"command": "C:\\Users\\guira\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\nosetests --with-json-extended tests_tp1.py", "time": 1516718443.463605, "cwd": "C:\\Users\\guira\\Desktop\\Python\\tp1"}}