{"modules": [{"name": "test_tp2", "nr_success": 0, "nr_failed": 1, "nr_error": 0, "testcases": [{"name": "test_mega", "result": "failed", "error": {"message": "AssertionError: [(1, 'Ma'), (3, 'Averell'), (4, 'William')] != [(1, 'Ma'), (3, 'Averell'), (4, 'William')]", "traceback": [{"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 59, "function": "testPartExecutor", "line": "yield"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\unittest\\case.py", "linenr": 605, "function": "run", "line": "testMethod()"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\case.py", "linenr": 198, "function": "runTest", "line": "self.test(*self.arg)"}, {"filename": "C:\\Users\\guira\\Desktop\\Python\\tp2\\test_tp2.py", "linenr": 45, "function": "test_mega", "line": "eq_(daltons, [(1, 'Ma'), (3, 'Averell'), (4, 'William')])"}, {"filename": "c:\\users\\guira\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\nose\\tools\\trivial.py", "linenr": 29, "function": "eq_", "line": "raise AssertionError(msg or \"%r != %r\" % (a, b))"}]}}]}], "metadata": {"command": "C:\\Users\\guira\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\nosetests --with-json-extended test_tp2.py", "time": 1516792825.2101228, "cwd": "C:\\Users\\guira\\Desktop\\Python\\tp2"}}